"""Independent architectural reference model for the neural-network accelerator."""

from .functional import (
    AcceleratorConfig,
    Config,
    FunctionalReference,
    ReferenceConfig,
    Sample,
    SampleRecord,
)
from .cycle import (
    AlignmentState,
    ArchitecturalCycleReference,
    CycleConfig,
    CycleInputs,
    CycleModel,
    CycleReference,
    CycleSampleRecord,
    CycleSnapshot,
    MatrixUpdatePackage,
    OutputEntry,
    ReductionUpdatePackage,
    ResultMetadata,
    SampleContext,
    SamplePosition,
    format_trace,
    print_trace,
)

__all__ = [
    "AcceleratorConfig",
    "Config",
    "FunctionalReference",
    "ReferenceConfig",
    "Sample",
    "SampleRecord",
    "AlignmentState",
    "ArchitecturalCycleReference",
    "CycleConfig",
    "CycleInputs",
    "CycleModel",
    "CycleReference",
    "CycleSampleRecord",
    "CycleSnapshot",
    "MatrixUpdatePackage",
    "OutputEntry",
    "ReductionUpdatePackage",
    "ResultMetadata",
    "SampleContext",
    "SamplePosition",
    "format_trace",
    "print_trace",
]
